[project]
name = "ci0202"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ghp-import>=2.1.0",
    "jupyter-book>=2.1.2",
    "myst>=1.0.4",
]
